spring:
  datasource:
    url: jdbc:mysql://199.193.255.99:3306/SpringBoot
    username: root
    password: Mysql938271654!
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-transaction-isolation: 2

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.bug.goods.pojo

#logging:
#  level:
#    root: debug

