spring:
  datasource:
    url: jdbc:mysql://199.193.255.99:3306/SpringBoot
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 采用隔离级别为读写提交
    tomcat:
      default-transaction-isolation: 2

  redis:
    port: 6379
    host: localhost
    timeout: 1000


  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.bug.goods.pojo

logging:
  level:
    root: debug

