spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    # 静态资源指定位置
    static-locations: classpath:/static/
logging:
  level:
    root: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.mvc.pojo
