spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    date-format: yyyy-MM-dd
  resources:
    # 静态资源指定位置
    static-locations: classpath:/static/

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: false
      location: D:/springboot_file_upload
logging:
  level:
    root: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.mvc.pojo
